# Generated by Django 2.2.1 on 2019-08-25 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type',
                 models.CharField(choices=[('group', 'a group for users'), ('single', 'only two users allowed')],
                                  default='single', max_length=10)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('contacts', models.ManyToManyField(to='accounts.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('dark', 'night mode'), ('light', 'a light theme')], default='dark',
                                           max_length=10)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=80)),
                ('type', models.CharField(
                    choices=[('accounts', 'from the accounts app'), ('conversation', 'from a conversation'),
                             ('default', 'default format')], default='default', max_length=30)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('sent', models.BooleanField(default=True)),
                ('date_sent', models.DateField(auto_now_add=True)),
                ('time_sent', models.TimeField(auto_now_add=True)),
                (
                    'conversation',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Contact')),
            ],
        ),
    ]
