# Generated by Django 2.2.1 on 2019-08-25 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.Conversation')),
            ],
        ),
    ]
