# Generated by Django 2.2.4 on 2019-08-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0002_pendingmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('group', 'a group for users'), ('single', 'only two users allowed')],
                                   default='couple', max_length=10),
        ),
    ]
