# Generated by Django 2.2.4 on 2019-08-29 19:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0003_auto_20190827_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date_sent',
        ),
        migrations.RemoveField(
            model_name='message',
            name='time_sent',
        ),
    ]
