# Generated by Django 2.2.4 on 2019-08-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0004_auto_20190829_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_sent',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='time_sent',
            field=models.TimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
