# Generated by Django 2.2.4 on 2019-08-31 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0006_delete_pendingmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='history',
            field=models.BooleanField(choices=[(True, 'save chat history in db'), (False, "don't save history in db")],
                                      default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='private_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('group', 'a group for users'), ('couple', 'only two users allowed')],
                                   default='couple', max_length=10),
        ),
    ]
