# Generated by Django 2.2.5 on 2019-09-15 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0007_auto_20190901_0222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('date_sent', 'time_sent')},
        ),
    ]
