# Generated by Django 2.2.5 on 2020-02-03 20:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0011_auto_20200203_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='contacts',
            new_name='participants',
        ),
    ]
