# Generated by Django 2.2.5 on 2020-02-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chat', '0012_auto_20200203_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', to='accounts.Contact'),
        ),
    ]
