# Generated by Django 2.2.4 on 2019-08-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='firends',
        ),
        migrations.AddField(
            model_name='contact',
            name='friends',
            field=models.ManyToManyField(related_name='_contact_friends_+', to='accounts.Contact',
                                         verbose_name='Friends'),
        ),
    ]
