# Generated by Django 2.2.5 on 2019-09-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_auto_20190830_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_contact_friends_+', to='accounts.Contact',
                                         verbose_name='Friends'),
        ),
    ]
