# Generated by Django 2.2.5 on 2019-09-16 14:14

from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_auto_20190916_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_pic',
            field=models.ImageField(default='default/default.png', upload_to=accounts.models.upload_contact_pic,
                                    verbose_name='Profile Picture'),
        ),
    ]
